---
title: "TNC Map"
editor: visual
format:
  dashboard:
    orientation: columns
---


## Column {width="30%"}

```{r, echo=FALSE}
library(sf)
library(leaflet)

TNC<-read.csv("data/CalGRO_well_locations_extended.csv")

Calgro_map <- leaflet(TNC) %>%
  addTiles() %>%
  addProviderTiles("Esri.WorldImagery") %>%
  setView(lng = -118.63, lat = 37.6, zoom = 6) %>%
  addCircleMarkers(color="blue",
    ~Longitude, ~Latitude,
    radius = 1.5,) 
Calgro_map
```

## Column {width="35%"}


```{r, echo=FALSE, warning=FALSE, include=FALSE}
my_shapefile <- st_read("data/shapefiles/TNCLands_CalGRO.shp")
my_shapefile_11 <- st_transform(my_shapefile, 4326)
my_shapefile_11 <- sf::st_zm(my_shapefile_11, drop = TRUE, what = "ZM")
my_shapefile_11 <- my_shapefile_11 |>
  st_zm(drop = TRUE, what = "ZM") |>
  st_transform(4326)
```

### Row {height="33%"}

```{r,echo=FALSE,warning=FALSE}
#| title: "[Visit Randall webpage](https://rickard11.github.io/CNRA_map/Randall.html)"
Randall <- leaflet(my_shapefile_11) %>%
  addTiles() %>%
  addProviderTiles("Esri.NatGeoWorldMap") %>%
  setView(lng = -118.5, lat = 35.25, zoom = 9) %>%
  addPolygons(
    color = "black", 
    fillColor = "pink",     # Border color
    weight = 1,          # Border width
    fillOpacity = 0.6,   # Fill transparency
    popup = ~LRM_TR_NA        # Optional: Add popups based on a column, e.g., 'NAME'
  )

Randall


```

### Row {height="33%"}

```{r, echo=FALSE}
#| title: "[Visit Las Piletas webpage](https://rickard11.github.io/CNRA_map/Las_Piletas.html)"

Las_Piletas <- leaflet(my_shapefile_11) %>%
  addTiles() %>%
  addProviderTiles("Esri.NatGeoWorldMap") %>%
  setView(lng = -120.1, lat = 35.3, zoom = 10) %>%
  addPolygons(
    color = "black", 
    fillColor = "pink",     # Border color
    weight = 1,          # Border width
    fillOpacity = 0.6,   # Fill transparency
    popup = ~LRM_TR_NA        # Optional: Add popups based on a column, e.g., 'NAME'
  )
Las_Piletas
```

### Row {height="33%"}

```{r, echo=FALSE}
#| title: "[Visit Dangermond webpage](https://rickard11.github.io/CNRA_map/Dangermond.html)"

Dangermond <- leaflet(my_shapefile_11) %>%
  addTiles() %>%
  addProviderTiles("Esri.NatGeoWorldMap") %>%
  setView(lng = -120.45, lat = 34.5, zoom = 10) %>%
  addPolygons(
    color = "black", 
    fillColor = "pink",     # Border color
    weight = 1,          # Border width
    fillOpacity = 0.6,   # Fill transparency
    popup = ~LRM_TR_NA        # Optional: Add popups based on a column, e.g., 'NAME'
  )
Dangermond
```

## Column {width="35%"}

### Row {height="33%"}

```{r, echo=FALSE}
#| title: "[Visit Santa Cruz Island webpage](https://rickard11.github.io/CNRA_map/Santa_Cruz_Island.html)"

Santa_Cruz_isl<- leaflet(my_shapefile_11) %>%
  addTiles() %>%
  addProviderTiles("Esri.NatGeoWorldMap") %>%
  setView(lng = -119.74, lat = 34, zoom = 10) %>%
  addPolygons(
    color = "black", 
    fillColor = "pink",     # Border color
    weight = 1,          # Border width
    fillOpacity = 0.6,   # Fill transparency
    popup = ~LRM_TR_NA        # Optional: Add popups based on a column, e.g., 'NAME'
  )
Santa_Cruz_isl
```

### Row {height="33%"}

```{r, echo=FALSE}
#| title: "[Visit Santa Clara River webpage](https://rickard11.github.io/CNRA_map/Santa_Clara_River.html)"

Santa_Clara <- leaflet(my_shapefile_11) %>%
  addTiles() %>%
  addProviderTiles("Esri.NatGeoWorldMap") %>%
  setView(lng = -119.05, lat = 34.36, zoom = 11) %>%
  addPolygons(
    color = "black", 
    fillColor = "pink",     # Border color
    weight = 1,          # Border width
    fillOpacity = 0.6,   # Fill transparency
    popup = ~LRM_TR_NA        # Optional: Add popups based on a column, e.g., 'NAME'
  )
Santa_Clara
```

### Row {height="33%"}

```{r, echo=FALSE}
#| title: "[Visit Parks Creek webpage](https://rickard11.github.io/CNRA_map/Santa_Parks_Creek.html)"

Parks <- leaflet(my_shapefile_11) %>%
  addTiles() %>%
  addProviderTiles("Esri.NatGeoWorldMap") %>%
  setView(lng = -122.5, lat = 41.46, zoom = 11) %>%
  addPolygons(
    color = "black", 
    fillColor = "pink",     # Border color
    weight = 1,          # Border width
    fillOpacity = 0.6,   # Fill transparency
    popup = ~LRM_TR_NA        # Optional: Add popups based on a column, e.g., 'NAME'
  )
Parks
```